# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  version "1.13.0"

  on_macos do
    on_intel do
      sha256 "5b9ba167cfa1a686bc2266516a9517d5d68ddb562d2bd2ac6b5b8fb9a9a367bf"
      url "https://github.com/thurstonsand/wt/releases/download/v#{version}/wt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0bf45e1640a010273a80d14454c8633615d159098dc95a1c78244fdde70cd822"
      url "https://github.com/thurstonsand/wt/releases/download/v#{version}/wt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "60996e443ab789b5f8be823068623c678954213c42a7b7a2bebb524b9bcc365e"
      url "https://github.com/thurstonsand/wt/releases/download/v#{version}/wt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5554068b0bb21c06dd883b8d46ac4b65df9c2ec5005049b76523df0c1729c0db"
      url "https://github.com/thurstonsand/wt/releases/download/v#{version}/wt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wt"
  desc "Friendly Git worktree manager"
  homepage "https://github.com/thurstonsand/wt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  # No zap stanza required

end
