# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  version "1.14.1"

  on_macos do
    on_intel do
      sha256 "ab933dc17d11ca1344414c11593a3e9af0a3bbb44955937ab38ff96354323d3c"
      url "https://github.com/thurstonsand/wt/releases/download/v#{version}/wt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bbead6959419877c84c975b27b209d6cb736c2b71bd7f5606946739dd9fd2f8b"
      url "https://github.com/thurstonsand/wt/releases/download/v#{version}/wt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bb2be2960152766a93abfc7c07ebac4ee5d0ed42d00e6213b927628398140789"
      url "https://github.com/thurstonsand/wt/releases/download/v#{version}/wt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4870074ed92bcd36009c3304241c7242349d71805b2cae4e88ae2b5d3e6396da"
      url "https://github.com/thurstonsand/wt/releases/download/v#{version}/wt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wt"
  desc "Friendly Git worktree manager"
  homepage "https://github.com/thurstonsand/wt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  # No zap stanza required

end
