# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  version "1.13.1"

  on_macos do
    on_intel do
      sha256 "0b9333096344b17352d9e4b748337509349855e7ad369637beef11c2f42640cb"
      url "https://github.com/thurstonsand/wt/releases/download/v#{version}/wt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f1217de1c9e74f0dfc20c3d16106ea19bbe0e23c47eca3784b65a6bef2dc05ca"
      url "https://github.com/thurstonsand/wt/releases/download/v#{version}/wt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8af3689a286a454b71a2831b1bc4eca4bfa74dfa596377ac526b8cb1a05ae8d2"
      url "https://github.com/thurstonsand/wt/releases/download/v#{version}/wt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ecc6d6168eef304a86111caa6dc39cd68fdf47474475e05b9f772c087d4f5c63"
      url "https://github.com/thurstonsand/wt/releases/download/v#{version}/wt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wt"
  desc "Friendly Git worktree manager"
  homepage "https://github.com/thurstonsand/wt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  # No zap stanza required

end
